# Generated by Django 4.2.3 on 2024-02-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coordonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipementActif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('coord_extremite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.coordonnees')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FibreOptique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('latence', models.FloatField()),
                ('bande_passante', models.FloatField()),
                ('nombre_de_brin', models.IntegerField()),
                ('mode_installation', models.CharField(max_length=255)),
                ('longueur_exploitable', models.FloatField()),
                ('longueur_supportee', models.FloatField()),
                ('interfaces_client_dispo', models.IntegerField()),
                ('interfaces_client_exploitable', models.IntegerField()),
                ('trajet', models.FileField(blank=True, null=True, upload_to='trajets/')),
                ('coord_extremite_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extremite_1', to='inventaire.coordonnees')),
                ('coord_extremite_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extremite_2', to='inventaire.coordonnees')),
                ('equipement_actif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.equipementactif')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.proprietaire')),
            ],
        ),
        migrations.AddField(
            model_name='equipementactif',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.proprietaire'),
        ),
        migrations.AddField(
            model_name='coordonnees',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.proprietaire'),
        ),
    ]
