# Generated by Django 4.2.3 on 2024-02-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='axe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventaire.axe'),
        ),
    ]
