# Generated by Django 4.2.3 on 2024-02-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_debit_technologie_servicesupporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='valeur',
            field=models.CharField(max_length=100),
        ),
    ]
