# Generated by Django 4.2.3 on 2024-02-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_alter_debit_valeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipementActif1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('constructeur', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicesupporte',
            name='debits',
        ),
        migrations.DeleteModel(
            name='Debit',
        ),
        migrations.AddField(
            model_name='equipementactif1',
            name='services_supportes',
            field=models.ManyToManyField(to='inventaire.servicesupporte'),
        ),
        migrations.AddField(
            model_name='equipementactif1',
            name='technologies',
            field=models.ManyToManyField(to='inventaire.technologie'),
        ),
    ]
