# Generated by Django 4.2.3 on 2024-02-14 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0006_equipementactif1_remove_servicesupporte_debits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordonnees',
            name='equipement',
            field=models.ManyToManyField(to='inventaire.equipementactif1'),
        ),
        migrations.AlterField(
            model_name='coordonnees',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(27)]),
        ),
        migrations.AlterField(
            model_name='coordonnees',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-17), django.core.validators.MaxValueValidator(-5)]),
        ),
    ]
