# Generated by Django 4.2.3 on 2024-02-14 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0010_coordonnees_axes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnees',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaire.proprietaire'),
        ),
    ]
