# Generated by Django 4.2.3 on 2024-02-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0011_alter_coordonnees_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnees',
            name='axes',
            field=models.ManyToManyField(to='inventaire.axe'),
        ),
    ]
