# Generated by Django 4.2.3 on 2024-02-15 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0013_remove_coordonnees_axes_coordonnees_axes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FibreOptique1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('nombre_de_brin', models.IntegerField()),
                ('mode_installation', models.CharField(max_length=255)),
                ('longueur_exploitable', models.FloatField()),
                ('longueur_supportee', models.FloatField()),
                ('interfaces_client_dispo', models.IntegerField()),
                ('interfaces_client_exploitable', models.IntegerField()),
                ('trajet', models.FileField(blank=True, null=True, upload_to='trajets/')),
                ('coord_extremite_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extremite_1_fibre', to='inventaire.coordonnees')),
                ('coord_extremite_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extremite_2_fibre', to='inventaire.coordonnees')),
            ],
        ),
    ]
