# Generated by Django 4.2.3 on 2024-02-15 01:01

import django.core.validators
from django.db import migrations, models
import inventaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0014_fibreoptique1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibreoptique1',
            name='trajet',
            field=models.FileField(blank=True, null=True, upload_to=inventaire.models.upload_json_path, validators=[django.core.validators.FileExtensionValidator(['json'])]),
        ),
    ]
