# Generated by Django 5.0.2 on 2024-05-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0015_alter_fibreoptique1_trajet'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='password',
            field=models.CharField(default='password123', max_length=128),
        ),
    ]
