# Generated by Django 5.0.2 on 2024-05-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0016_proprietaire_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='role',
            field=models.CharField(default='user', max_length=5),
        ),
    ]
