# Generated by Django 5.0.2 on 2024-05-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0018_alter_proprietaire_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='role',
            field=models.CharField(default='user', max_length=5),
        ),
    ]
